language: R
cache: packages

# https://github.com/travis-ci/travis-ci/issues/6850
before_install:
  Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
