language: r
cache: packages
sudo: required
dist: trusty

# https://github.com/travis-ci/travis-ci/issues/6850
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
  - sudo apt-get install libv8-dev
  - sudo apt-get install aptitude -y
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

r_packages:
  - covr
  - rgdal

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
